@startuml
title Care Plan Business Actors

left to right direction
skinparam packageStyle rectangle
scale 0.8

' ========= Actors =========
actor Patient as PAT
actor "HC Professional" as HCP
actor "HC Provider (Org)" as ORG
actor Relatives as REL
actor Caregiver as CARG


note right of PAT
Subject of the Care Plan. An active participant who can access,
share and record assigned care plan actions.
end note

note right of HCP
Professional role responsible for clinical
use and management of the care plan.
end note

note right of ORG
Provider organisation supporting oversight,
coordination and outcome monitoring.
end note

note right of REL
Authorised family participant supporting
practical care plan activities.
end note

note right of CARG
Day-to-day support role helping execute,
record and assessment and follow up actions.
end note



@enduml
