@startuml
title Care Plan Patient Use Case

left to right direction
skinparam packageStyle rectangle

actor "HC Professional" as HCP
actor Clinician as CLIN
actor Nurse as NUR


CLIN -|> HCP
NUR  -|> HCP

rectangle "Care Plan Services" {
  usecase "Search & see care plan" as UC_View
  usecase "Share care plan" as UC_Share
  usecase "Execute & record actions" as UC_Exec

  usecase "Define care plan" as UC_Define
  usecase "Care plan mgmt. & execution" as UC_Mgmt

  usecase "Update care plan" as UC_Update
  usecase "See the care plan" as UC_See
  usecase "Monitor care plan\n(incl. outcomes)" as UC_Monitor
}

HCP --> UC_View
HCP --> UC_Share
HCP --> UC_Exec
CLIN --> UC_Define
HCP --> UC_Mgmt


UC_Mgmt ..> UC_Update : <<include>>
UC_Mgmt ..> UC_See    : <<include>>
UC_Mgmt ..> UC_Monitor: <<include>>

UC_View ..> UC_See    : <<include>>
@enduml
