@startuml
actor "Natural Person" as NatPerson
participant "xShare Yellow Button" as xShare
database "Natural Person's Storage" as Storage

==== Natural Person authentication (pre-condition) ====
group #00FF00 "Natural Person Authentication"
NatPerson -[#blue]> NatPerson: Natural Person Authenticates in the user interface
end group

==== Search and Select Health Information ====
group Search and Select Natural Person's Health data
NatPerson -> xShare: Search Natural Person's Health Data
activate xShare
xShare -> xShare: Search Natural Person's Health Data
return: Shows Natural Person's available Health Data
NatPerson -> xShare: Selects health data to download or share
activate xShare
end group

==== Retrieve and Format Health Information ====
group Retrieve and Format Natural Person's Health data
xShare-> xShare: Retrieve Natural Person's Health Data
xShare-> xShare: EEHRxF data
end group

==== Selects Data Transformation Option ====
opt select Data Transformation option
NatPerson -> xShare: Selects transformation option (human-readable format, \n anonymisation, password protection, translation, digital signature)
xShare -> xShare: Transformed data
end opt

==== Download Health Information ====
group Download Natural Person's Health Information
NatPerson -> xShare: Downloads Natural Person's Health Data
xShare -> Storage: Natural Person's Health Information is stored
deactivate xShare
end group

@enduml